### ISSUE TITLE
How to reduce the size of 7 Segment font Font7srle? 

### ISSUE THREAD

**Issue by Amitabh-wq** [Bodmer/TFT_ST7735#22]
Hi Bodmer.
I'm using your 7-segment font (which is very nice) in a project with Arduino Nano + TFT ST7735 160x128.
I would like to reduce the size of this font to half or even smaller.
The question is, how do I reduce the size of this font?
Thanks.

**Comment by Bodmer** [comment]
Unfortunately there is no feature to reduce the font size.

**Comment by Amitabh-wq** [comment]
Could you please give me a hint on how to create a font identical to this one, but with a smaller size, to use in the TFT_ST7735 library? Thanks.

**Comment by Bodmer** [comment]
A long time ago I wrote an Arduino sketch that created the fonts from bitmaps, this then needed some manual editting. The bitmaps were generated by a software tool from crystalfontz which does not seem to exist anymore. Unfortunately during a PC upgrade the sketch and tool were lost. Writing again from scratch is on my todo list but is not a priority due to other work at the moment.

FYI a character is drawn as a raster scan within a box size of the characters width and global font height. The RLE format is a byte, the top bit is a flag, the least significant 7 bits are a 7 bit number (0-127). If the flag is 1 then foreground pixels are plotted, if it is 0 the background pixels are plotted. The number of pixels to plot is the 7 bit number +1.

So, for example, the encoded sequence "0x81, 0x1F" means plot 2 pixels in foreground then 32 pixels in background.

**Comment by Amitabh-wq** [comment]
Thanks for the information!
